language: python
python:
  - "2.7"
#  - "3.4"
  - "3.5"
  - "3.6"

#stages:
#  - test
#  - build
#  - deploy

env:
  - PYTHONPATH=$PYTHONPATH:./src

install:
  - pip install -r test_requirements.txt

script:
  - pytest

jobs:
  include:
    - stage: deploy documentation
      python: 3.6
      install: pip install sphinx
      script: sphinx-build -Ean -b html -j auto -D todo_include_todos=0 ./doc ./doc/_build/html ; touch ./doc/_build/html/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./doc/_build/html
        on:
          branch: master

