language: python
python:
  - "2.7"
#  - "3.4"
  - "3.5"
  - "3.6"

stages:
  - test
  - build
  - deploy

env:
  - PYTHONPATH=$PYTHONPATH:./src

install:
  - pip install -r test_requirements.txt

script:
  - pytest

jobs:
  include:
    - stage: build
      install: pip install sphinx
      script: sphinx-build -Ean -b html -j auto -D todo_include_todos=0 ./doc ./doc/_build/html
    - stage: deploy
      script: echo "deploying"


#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep_history: true
#  on:
#    branch: master

